name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup msbuild
      - uses: microsoft/setup-msbuild@v1.1

      # Build
      - run: msbuild FreddiChat.sln -t:rebuild -verbosity:diag -property:Configuration=Release
